apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: gito
    user: postgres
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 160
      tlsMode: disable
    version: 1
